apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredResources
metadata:
  name: container-must-have-limits
spec:
  enforcementAction: warn
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    apiGroups: [""]
    kinds: ["Pod"]
    requiredFiles:
      - limits
    resources:
      - cpu
      - memory