apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: policy-controller
  namespace: argocd
spec:
  project: default
  source:
    chart: policy-controller
    repoURL: https://sigstore.github.io/helm-charts
    targetRevision: 0.*
    values: |
      webhookConfig:
        objectSelector:
          matchExpressions:
            - key: policy.sigstore.dev/include
              operator: In
              values: ["true"]
  destination:
    server: https://kubernetes.default.svc
    namespace: cosign-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true