apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-creds
  namespace: demo
spec:
  refreshInterval: 1m
  secretStoreRef: # Cấu hình tham chiếu đến resource lưu thông tin kết nối tới AWS
    name: aws-store
    kind: SecretStore
  target:
    name: db-secret # Tên K8s Secret sẽ được sinh ra tự động
  data: # Khối này sài để mapping dữ liệu giữa k8s và aws
    - secretKey: password # Key trong k8s Secrect có tên là password
      remoteRef:
        key: demo/db/password # Đường dẫn secret trên AWS Secrets Manager